/* Generated with cbindgen */
/* Schlussel - OAuth 2.0 with PKCE for CLI applications */

#ifndef SCHLUSSEL_H
#define SCHLUSSEL_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdbool.h>

/**
 * Error codes for C API
 */
typedef enum SchlusselSchlusselError {
  Ok = 0,
  OutOfMemory = 1,
  InvalidArgument = 2,
  NotFound = 3,
  Unknown = 99,
} SchlusselSchlusselError;

/**
 * In-memory storage implementation
 *
 * Thread-safe in-memory storage for sessions and tokens.
 * Suitable for testing and simple use cases.
 */
typedef struct SchlusselMemoryStorage SchlusselMemoryStorage;

/**
 * OAuth 2.0 client
 *
 * Manages the OAuth authorization code flow with PKCE.
 */
typedef struct SchlusselOAuthClient_MemoryStorage SchlusselOAuthClient_MemoryStorage;

/**
 * Token refresher with concurrency control
 *
 * Ensures only one refresh happens at a time for a given token key.
 */
typedef struct SchlusselTokenRefresher_MemoryStorage SchlusselTokenRefresher_MemoryStorage;

/**
 * OAuth configuration for C API
 */
typedef struct SchlusselSchlusselOAuthConfig {
  const char *client_id;
  const char *authorization_endpoint;
  const char *token_endpoint;
  const char *redirect_uri;
  const char *scope;
} SchlusselSchlusselOAuthConfig;

/**
 * Auth flow result for C API
 */
typedef struct SchlusselSchlusselAuthFlow {
  char *url;
  char *state;
} SchlusselSchlusselAuthFlow;

/**
 * Get library version
 */
const char *schlussel_version(void);

/**
 * Create in-memory storage
 */
struct SchlusselMemoryStorage *schlussel_storage_memory_create(void);

/**
 * Destroy storage
 */
void schlussel_storage_destroy(struct SchlusselMemoryStorage *storage);

/**
 * Create OAuth client
 */
struct SchlusselOAuthClient_MemoryStorage *schlussel_oauth_create(const struct SchlusselSchlusselOAuthConfig *config,
                                                                  struct SchlusselMemoryStorage *storage);

/**
 * Destroy OAuth client
 */
void schlussel_oauth_destroy(struct SchlusselOAuthClient_MemoryStorage *client);

/**
 * Start OAuth flow
 */
enum SchlusselSchlusselError schlussel_oauth_start_flow(struct SchlusselOAuthClient_MemoryStorage *client,
                                                        struct SchlusselSchlusselAuthFlow *result);

/**
 * Free auth flow result
 */
void schlussel_auth_flow_free(struct SchlusselSchlusselAuthFlow *result);

/**
 * Create token refresher
 */
struct SchlusselTokenRefresher_MemoryStorage *schlussel_token_refresher_create(struct SchlusselOAuthClient_MemoryStorage *client);

/**
 * Destroy token refresher
 */
void schlussel_token_refresher_destroy(struct SchlusselTokenRefresher_MemoryStorage *refresher);

/**
 * Wait for refresh to complete
 */
void schlussel_token_refresher_wait(struct SchlusselTokenRefresher_MemoryStorage *refresher,
                                    const char *key);

#endif  /* SCHLUSSEL_H */
